language: python

matrix:
  include:
    # Linux Python 2
    - sudo: required
      language: python
      python: 2.7
      services: docker
      env: PYTHON=python

    # Linux Python 3
    - sudo: required
      language: python
      python: 3.5
      services: docker
      env: PYTHON=python

    # Linux Python 3
    - sudo: required
      language: python
      python: 3.6
      services: docker
      env: PYTHON=python

    # macOS Python 2
    - os: osx
      env: PYTHON=python2

    # macOS Python 3
    - os: osx
      env: PYTHON=python3
      before_install:
        - brew update
        - brew outdated python || brew upgrade python

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install cython numpy"
    - CIBW_TEST_REQUIRES=pytest-cov
    - CIBW_TEST_COMMAND="cd {project}/tests && py.test --cov gstools --cov-report term-missing -v ."

script:
  - python -m pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - python -m cibuildwheel --output-dir wheelhouse
  - rm -rf dist
  - python -m pip install cython numpy
  - python setup.py sdist
  - python -m pip install pytest-cov
  # final coveralls for linux only
  - python -m pip install matplotlib coveralls
#  - python -m coverage run --source=gstools setup.py test
  - python -m pytest --cov gstools --cov-report term-missing -v tests/
  - python -m coveralls

after_success:
  - python -m pip install twine
#  - python -m twine upload --skip-existing wheelhouse/*.whl
#  - python -m twine upload --skip-existing dist/*.tar.gz
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
#  - |
#    if [[ $TRAVIS_TAG ]]; then
#      python -m pip install twine
#      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#    fi
# ignore tag for a moment

notifications:
  email:
    recipients:
    - info@geostat-framework.org
