language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_SKIP="cp34-* cp37-*"
    - CIBW_BEFORE_BUILD="pip install cython numpy"
    - CIBW_TEST_REQUIRES=pytest-cov
    - CIBW_TEST_COMMAND="cd {project}/tests && py.test --cov gstools --cov-report term-missing -v ."

script:
  - $PIP install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
  - rm -rf dist
  - python -m pip install cython numpy
  - python setup.py sdist
  - python -m pip install pytest-cov
  # final coveralls for linux only
  - python -m pip install -r docs/requirements.txt
  - python -m pip install matplotlib coveralls
#  - python -m coverage run --source=gstools setup.py test
  - python -m pytest --cov gstools --cov-report term-missing -v tests/
  - python -m coveralls

after_success:
  - python -m pip install twine
#  - python -m twine upload --skip-existing wheelhouse/*.whl
#  - python -m twine upload --skip-existing dist/*.tar.gz
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
#  - |
#    if [[ $TRAVIS_TAG ]]; then
#      python -m pip install twine
#      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#    fi
# ignore tag for a moment

notifications:
  email:
    recipients:
    - info@geostat-framework.org
