language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r docs/requirements.txt
  - pip install -v .
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py build_ext --inplace

script:
  - cd tests/
  - py.test --cov gstools --cov-report term-missing -v .

after_success:
  - coveralls

notifications:
  email:
    recipients:
    - info@geostat-framework.org
