language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r docs/requirements.txt
  - pip install -v .
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py build_ext --inplace

script:
  - py.test --cov gstools --cov-report term-missing -v tests/

after_success:
  - coveralls
  - rm -r build/
  - rm gstools/variogram/*.so
  - rm gstools/variogram/estimator.c

notifications:
  email:
    recipients:
    - info@geostat-framework.org
