language: python

matrix:
  include:
    - name: "Linux py27"
      sudo: required
      language: python
      python: 2.7
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp27-*"
        - COVER="off"
        - INS_CIBW="$PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "Linux py34"
      sudo: required
      language: python
      python: 3.4
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp34-*"
        - COVER="off"
        - INS_CIBW="$PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "Linux py35"
      sudo: required
      language: python
      python: 3.5
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp35-*"
        - COVER="off"
        - INS_CIBW="$PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "Linux py36"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp36-*"
        - COVER="on"
        - INS_CIBW="$PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    # https://github.com/travis-ci/travis-ci/issues/9815
    - name: "Linux py37"
      sudo: required
      language: python
      python: 3.7
      dist: xenial
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp37-*"
        - COVER="off"
        - INS_CIBW="$PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.5 cython==0.28.3"

    - name: "MacOS py27"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp27-*"
        - COVER="off"
        - INS_CIBW="sudo $PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "MacOS py34"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp34-*"
        - COVER="off"
        - INS_CIBW="sudo $PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "MacOS py35"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp35-*"
        - COVER="off"
        - INS_CIBW="sudo $PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "MacOS py36"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp36-*"
        - COVER="off"
        - INS_CIBW="sudo $PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.13.0 cython==0.26"

    - name: "MacOS py37"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp37-*"
        - COVER="off"
        - INS_CIBW="sudo $PIP install cibuildwheel==0.10.1"
        - CIBW_BEFORE_BUILD="pip install numpy==1.14.5 cython==0.28.3"

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_TEST_REQUIRES=pytest-cov
    # inplace cython build and test run
    - CIBW_TEST_COMMAND="cd {project} && python setup.py build_ext --inplace && py.test --cov gstools --cov-report term-missing -v {project}/tests"

script:
  # create wheels
  - eval ${INS_CIBW}
  - cibuildwheel --output-dir wheelhouse
  # create source dist for pypi and create coverage (only once for linux py3.6)
  - |
    if [[ $COVER == "on" ]]; then
      rm -rf dist
      python -m pip install numpy==1.13.0 cython==0.26
      python setup.py sdist
      python -m pip install pytest-cov coveralls
      python -m pip install -r docs/requirements.txt
      python setup.py build_ext --inplace
      python -m pytest --cov gstools --cov-report term-missing -v tests/
      python -m coveralls
    fi

after_success:
  # pypi upload (test allways and official on TAG)
  # cmarkgfm needed for README.md: https://github.com/pypa/readme_renderer/blob/7bf7529296acfa7db0edf7914cb4571d691b63ee/setup.py#L77
  - python -m pip install twine cmarkgfm>=0.2.0
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload --skip-existing wheelhouse/*.whl
      python -m twine upload --skip-existing dist/*.tar.gz
    fi

notifications:
  email:
    recipients:
    - info@geostat-framework.org

