language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=geostatframework
#    - CIBW_TEST_REQUIRES=pytest-cov coveralls
#    - CIBW_TEST_COMMAND="py.test --cov gstools --cov-report term-missing -v {project}/tests"
# tests take for ever.. maybe separate?

script:
  - $PIP install -r {project}/docs/requirements.txt
  - $PIP install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#  - |
#    if [[ $TRAVIS_TAG ]]; then
#      python -m pip install twine
#      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#    fi
# ignore tag for a moment

notifications:
  email:
    recipients:
    - info@geostat-framework.org
