language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_TEST_REQUIRES=pytest-cov coveralls cython numpy
    - CIBW_TEST_COMMAND="cd {project} && python setup.py build_ext --inplace && py.test --cov gstools --cov-report term-missing -v tests && coveralls"

script:
  - $PIP install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#  - |
#    if [[ $TRAVIS_TAG ]]; then
#      python -m pip install twine
#      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
#    fi
# ignore tag for a moment

notifications:
  email:
    recipients:
    - info@geostat-framework.org
