environment:
  global:
    TWINE_USERNAME: geostatframework

  matrix:
    - PYTHON: "C:\\Python27"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python27-x64"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python34"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python34-x64"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python35"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python35-x64"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python36"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python36-x64"
      CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26
    - PYTHON: "C:\\Python37"
      CIBW_BEFORE_BUILD: pip install numpy==1.14.5 cython==0.28.3
    - PYTHON: "C:\\Python37-x64"
      CIBW_BEFORE_BUILD: pip install numpy==1.14.5 cython==0.28.3

build_script:
  - pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --skip-existing wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels