environment:
  TWINE_USERNAME: geostatframework
  CIBW_SKIP: "cp34-* cp37-*"
  CIBW_BEFORE_BUILD: pip install cython numpy

build_script:
  - pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --skip-existing wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels