[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.5",
    "numpy>=1.14.5,<2.0",
    "Cython>=0.28.3,<3.0",
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["gstools"]
omit = [
    "*docs*",
    "*examples*",
    "*tests*",
    "*/gstools/covmodel/plot.py",
    "*/gstools/field/plot.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
]

[tool.black]
line-length = 79
target-version = [
    "py36",
    "py37",
    "py38",
]
